# Generated by Django 2.2 on 2021-01-30 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='16497084.jpeg', null=True, upload_to='image/')),
                ('offer_name', models.CharField(default='', max_length=200)),
                ('valid_from', models.CharField(default='', max_length=200)),
                ('valid_till', models.CharField(default='', max_length=200)),
                ('discount', models.CharField(default='', max_length=200)),
                ('CustomUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
